version: "3.8"

services:

  wordpress:
    image: wordpress:6.4.3-php8.2-apache
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    secrets:
      - db_password


  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - db:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    secrets:
      - db_password
      - db_root_password

secrets:
   db_password:
     file: ./run/secrets/db_password.txt
   db_root_password:
     file: ./run/secrets/db_root_password.txt

volumes:
  wordpress:
  db:
